# Generated by Django 2.2 on 2023-02-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_choose_us',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
