# Generated by Django 2.2 on 2023-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230208_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='Learnmore',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
