# Generated by Django 4.1.6 on 2023-02-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aboutus_id_alter_contact_id_alter_ourteam_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteam',
            old_name='Testimony_Photo',
            new_name='photo',
        ),
    ]
