# Generated by Django 4.1.6 on 2023-02-08 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_testimony_photo_ourteam_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
