# Generated by Django 4.1.6 on 2023-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_slide_logo_alter_ourteam_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=400)),
                ('Full_name', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='projects/')),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='photo',
            new_name='image',
        ),
    ]
